### PR TITLE
Frontend: Add return home button in navbar

### PR DESCRIPTION
**Pull request by DesmondTo**
Clicking on `PeerPrep` on the navbar will navigate to "/home" path.

### CODE REVIEW

**Review by xyliew25 — APPROVED** [review]
LGTM

**Comment by xyliew25** [comment]
Eh wait, just realized navigating to home might not be ideal as the home page is not accessible by users who are not signed in.

**Comment by DesmondTo** [comment]
> Eh wait, just realized navigating to home might not be ideal as the home page is not accessible by users who are not signed in.

@xyliew25  I think it's fine, for example when the user not signed in, clicking on the button will just redirect them back to sign in page

**Comment by xyliew25** [comment]
@DesmondTo hm I guess it's alright for now then

**Pull request merged**
